# -*- coding: utf-8 -*-
"""ml-leakage-pipeline-Arun Kumar T.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mVRtV2lVGrv1PZuCa8SqIyRtvuWyunpM
"""

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Generate sample data....
X, y = make_classification(n_samples=1000, n_features=10, random_state=42)

# Scaling before splitting (data leakage)
                  # its learn all the entri data set including the test data..
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data before starting the model ....

# in this test leak to the train data itys fails occur....
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Train model
model = LogisticRegression()
model.fit(X_train, y_train)

# Predictions
train_acc = accuracy_score(y_train, model.predict(X_train))
test_acc = accuracy_score(y_test, model.predict(X_test))

print("Train Accuracy:", train_acc)
print("Test Accuracy:", test_acc)


# we hav eto check all the code its done by the  order



#data-split into features and labels-scaling-model=train-test-predict and we need to add the new data if we need....

# Task 02 ....
# to import the library what we need ....
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

# Generate data(sample)
X, y = make_classification(n_samples=1000, n_features=10, random_state=42)

#sployt the data into x,y....

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# in this we need to train the 80% data and test with the 20%...
# pipeline is the safest there is no leakage.....
pipeline=Pipeline([
    ('scaler',StandardScaler()),
    ('model',LogisticRegression())
    ])

# Cross-validation
scores = cross_val_score(pipeline, X_train, y_train, cv=5)

print("Cross-validation Accuracy:", scores)
print("Mean Accuracy:", scores.mean())
print("Standard Deviation:", scores.std())

# Task 03
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Generate dataset
X, y = make_classification(n_samples=1000, n_features=10, random_state=42)

# SAME split as Task 2
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42

    # here traing with 80% and testing with the 20%./..
)

depths = [1, 5, 20]#samll,medium ,large

print("Depth | Train Accuracy | Test Accuracy")
print("---------------------------------------")

for depth in depths:
    model = DecisionTreeClassifier(max_depth=depth, random_state=42)
    model.fit(X_train, y_train)
    # trau=ing the model with features

    # Predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Accuracy prediction
    train_acc = accuracy_score(y_train, y_train_pred)
    test_acc = accuracy_score(y_test, y_test_pred)

    print(f"{depth:5d} | {train_acc:.3f}         | {test_acc:.3f}")